development:
  adapter: postgresql
  encoding: unicode
  database: ror5_template
  host: localhost
  pool: 5
  username: postgres
  password: qazwsx12
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: ror5_template-test
  host: localhost
  pool: 5
  username: postgres
  password: qazwsx12
  port: 5432
